/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CardsData: typeof import('./src/components/CardsData.vue')['default']
    CardsSection: typeof import('./src/components/CardsSection.vue')['default']
    copy: typeof import('./src/components/ProductsTable copy.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProductsTable: typeof import('./src/components/ProductsTable.vue')['default']
    ProductsTableApi: typeof import('./src/components/ProductsTableApi.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
